### ISSUE TITLE
[feature] multiple sprites (one per folder for instance)

### ISSUE THREAD

**Issue by intellix** [aslansky/css-sprite#21]
Just come from compass where I have a folder/sprite structure like:

```
sprites
    global # sprites that exist all over the site and homepage
    account # sprites that are used on the account section
    games # sprites that only appear on the games page
```

this creates 3 sprites: global, account and games.
- When you land on the site for the first time, you end up downloading global.png so you get images that are everywhere and on the homepage.
- When you go to the account section, you end up downloading account.png as well.

Currently, all sprites are downloaded at once, which could be huge and unnecessary.

So I think the gulp task would look something like:

```js
gulp.task('sprites', function () {
  return gulp.src('/src/images/sprites/**/*.png')
    .pipe(sprite({
 //      name: 'sprite.png', // no more name property, it should be dynamic
      style: '_sprite.scss',
      cssPath: '/images',
      prefix: 'sprite',
      processor: 'scss'
    }))
    .pipe(gulpif('*.png', gulp.dest('/src/images/'), gulp.dest('/src/styles/')))
});
```

Which would create: global.png, payment.png, games.png and then one sprites.scss file like: 
```scss
$global-blah: -5px -5px 50px 10px;
$account-blah: -5px -25px 77px 20px;
$games-blah: -5px -55px 51px 24px;

// mixin definitions etc
```

The SCSS seems correct to me, it's just the image generation

**Comment by Avien** [comment]
Another issue with multiple tasks is, at least on scss version it generates a multiple '.icon' classes for each scss file, each with a different generated background image url so the last included overrides all previous ones
it should generate '.icon-{name-given-in-task}' instead

**Comment by Avien** [comment]
I now see there is a 'prefix' options just for that

**Comment by jedmao** [comment]
I agree with @intellix that multiple sprites should be created for each folder, just like [Compass](http://compass-style.org/help/tutorials/spriting/). I also think the naming convention should be like [BEM](http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/) to avoid naming collisions. Using the [nth function](http://sass-lang.com/documentation/Sass/Script/Functions.html#nth-instance_method) also seems a bit tacky in the templates. I propose, instead, the use of [Sass 3.3 maps](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#maps).

If these paradigms were followed, we could have some very BEM-friendly Sass, like so:

```scss
.header__logo {
	@include sprite(app, logo);

	&--dark {
		@include sprite(app, logo--dark);
	}
}
```

This should generate the following CSS:

```css
.header__logo,
.header__logo--dark {
	background: url('base64-encoded-garbage') no-repeat;
}

.header__logo {
	background-position: 0 0;
	width: 100px;
	height: 50px;
}

.header__logo--dark {
	background-position: 0 -50px;
	width: 100px;
	height: 50px;
}
```

This can be made possible with the following `_app-sprite.scss` partial.

```hbs
${{folder_name}}-sprite: (
  {{#items}}
    {{image_name}}: (
      offset-x: {{px.offset_x}},
      offset-y: {{px.offset_y}},
      width: {{px.width}},
      height: {{px.height}}
    ),
  {{/items}}
);

{{#sprite}}
%{{folder_name}}-sprite {
  background: url('{{{escaped_image}}}') no-repeat;
}
{{/sprite}}
```

As you can see, the template's job here is to write data into a Sass map data structure, which the mixins can leverage. Also, a silent class is created with a BEM naming convention so it can be extended by the sprite mixin.

The sprite mixins would look something like this:

```scss
@function sprite-width($folder-name, $image-name) {
  @return map-get(map-get($folder-name, $image-name), width);
}

@function sprite-height($folder-name, $image-name) {
  @return map-get(map-get($folder-name, $image-name), height);
}

@mixin sprite($folder-name, $image-name) {
	@extend %#{$folder-name}-sprite;
	$image-props: map-get($folder-name, $image-name);
	background-position:
		map-get($image-props, offset-x)
		map-get($image-props, offset-y)
	;
	width: sprite-width($folder-name, $image-name);
	height: sprite-height($folder-name, $image-name);
}
```

Let the user decide what display type to use, be it `block` or `inline-block`. That's an implementation detail that shouldn't be of concern to sprite generation.

The only thing missing at this point is one more file that needs to be generated. This file isn't a partial like the rest, so we'll call it `sprites.scss`.

```scss
@include "sprite-mixins";
@include "app-sprite";
// include more sprite images
```

See how the inclusion of the sprite-mixins is only done once? If they need something more custom then they can create a Sass file of their own and include only the sprites they want in that file.
